//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideothequeProjet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actors
    {
        public Actors()
        {
            this.Movies = new HashSet<Movies>();
        }
    
        public int actorID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string iconURL { get; set; }
    
        public virtual ICollection<Movies> Movies { get; set; }
    }
}
