//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideothequeProjet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Movies
    {
        public Movies()
        {
            this.DVD = new HashSet<DVD>();
            this.Actors = new HashSet<Actors>();
            this.Directors = new HashSet<Directors>();
            this.FilmTypes = new HashSet<FilmTypes>();
        }
    
        public int movieID { get; set; }
        [Display(Name = "Titre")]
        public string title { get; set; }
        [Display(Name = "Synopsis")]
        public string synopsis { get; set; }
        [Display(Name = "Durée")]
        public Nullable<int> duration { get; set; }
        [Display(Name = "Année de sortie")]
        public Nullable<int> year { get; set; }
        [Display(Name = "Note")]
        public Nullable<decimal> note { get; set; }
        [Display(Name = "Prix")]
        public decimal price { get; set; }
    
        public virtual ICollection<DVD> DVD { get; set; }
        public virtual ICollection<Actors> Actors { get; set; }
        public virtual ICollection<Directors> Directors { get; set; }
        [Display(Name = "Genre")]
        public virtual ICollection<FilmTypes> FilmTypes { get; set; }
    }
}
