//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideothequeProjet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentingDetails
    {
        public int RentingDetailsID { get; set; }
        public int DVDID { get; set; }
        public int rentingID { get; set; }
        public decimal price { get; set; }
        public bool back { get; set; }
        public System.DateTime dateStart { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
    
        public virtual DVD DVD { get; set; }
        public virtual Rentings Rentings { get; set; }
    }
}
