//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideothequeProjet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Rentings
    {
        public Rentings()
        {
            this.RentingDetails = new HashSet<RentingDetails>();
        }
    
        public int rentingID { get; set; }
        public int customerID { get; set; }        
        public int adminID { get; set; }
        [Display(Name = "Date de près")]
        public System.DateTime dateStart { get; set; }
        [Display(Name = "Date de rendu prévu")]
        public Nullable<System.DateTime> dateEnd { get; set; }
        [Display(Name = "Prix")]
        public double cost { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual ICollection<RentingDetails> RentingDetails { get; set; }
        public virtual Users Users { get; set; }
    }
}
