//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideothequeProjet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rentings
    {
        public Rentings()
        {
            this.RentingDetails = new HashSet<RentingDetails>();
        }
    
        public int rentingID { get; set; }
        public int customerID { get; set; }
        public int userID { get; set; }
        public Nullable<decimal> cost { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual ICollection<RentingDetails> RentingDetails { get; set; }
        public virtual Users Users { get; set; }
    }
}
