//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideothequeProjet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjetVideoEntities : DbContext
    {
        public ProjetVideoEntities()
            : base("name=ProjetVideoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actors> Actors { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Directors> Directors { get; set; }
        public virtual DbSet<DVD> DVD { get; set; }
        public virtual DbSet<FilmTypes> FilmTypes { get; set; }
        public virtual DbSet<Movies> Movies { get; set; }
        public virtual DbSet<RentingDetails> RentingDetails { get; set; }
        public virtual DbSet<Rentings> Rentings { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
